"""Validate status/status.toml and render status/STATUS.md (ADR-011).

Usage:
    python scripts/status/render_status.py          # validate + write STATUS.md
    python scripts/status/render_status.py --check  # fail if STATUS.md is stale (for CI)

Standard library only (Python >= 3.11).
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "status" / "status.toml"
TARGET = ROOT / "status" / "STATUS.md"

MODULE_STATUSES = {"NOT_STARTED", "DESIGN", "IN_PROGRESS", "BLOCKED", "IN_REVIEW", "DONE"}
TASK_STATUSES = {"TODO", "DOING", "BLOCKED", "DONE"}
ICONS = {
    "NOT_STARTED": "⚪",
    "DESIGN": "🔵",
    "IN_PROGRESS": "🟡",
    "BLOCKED": "🔴",
    "IN_REVIEW": "🟣",
    "DONE": "🟢",
}


class StatusError(ValueError):
    """Raised when status.toml is inconsistent."""


def validate(data: dict[str, Any]) -> None:
    errors: list[str] = []
    phase_ids = [p["id"] for p in data.get("phases", [])]
    module_ids = [m["id"] for m in data.get("modules", [])]

    for label, ids in (("phase", phase_ids), ("module", module_ids)):
        dupes = {i for i in ids if ids.count(i) > 1}
        if dupes:
            errors.append(f"duplicate {label} ids: {sorted(dupes)}")

    if data["project"]["current_phase"] not in phase_ids:
        errors.append(f"project.current_phase {data['project']['current_phase']!r} is not a phase")

    for p in data.get("phases", []):
        if p["status"] not in MODULE_STATUSES:
            errors.append(f"phase {p['id']}: invalid status {p['status']!r}")

    for m in data.get("modules", []):
        mid = m["id"]
        if m["status"] not in MODULE_STATUSES:
            errors.append(f"{mid}: invalid status {m['status']!r}")
        for ph in m.get("phases", []):
            if ph not in phase_ids:
                errors.append(f"{mid}: unknown phase {ph!r}")
        if m["status"] == "BLOCKED" and not m.get("blocked_by"):
            errors.append(f"{mid}: status BLOCKED requires blocked_by")
        tasks = m.get("tasks", [])
        for t in tasks:
            if t["status"] not in TASK_STATUSES:
                errors.append(f"{mid}: task {t['title']!r} has invalid status {t['status']!r}")
        if m["status"] == "DONE" and any(t["status"] != "DONE" for t in tasks):
            errors.append(f"{mid}: marked DONE but has unfinished tasks")

    for d in data.get("dod", []):
        if d["module"] not in module_ids:
            errors.append(f"DoD item {d['item']!r}: unknown module {d['module']!r}")

    if errors:
        raise StatusError("status.toml is invalid:\n  - " + "\n  - ".join(errors))


def _progress(tasks: list[dict[str, Any]]) -> tuple[int, int]:
    return sum(t["status"] == "DONE" for t in tasks), len(tasks)


def _bar(done: int, total: int, width: int = 10) -> str:
    if total == 0:
        return "—"
    filled = round(width * done / total)
    return f"`{'█' * filled}{'░' * (width - filled)}` {done}/{total}"


def render(data: dict[str, Any]) -> str:
    project = data["project"]
    modules = data["modules"]
    all_tasks = [t for m in modules for t in m.get("tasks", [])]
    dod = data.get("dod", [])

    out: list[str] = [
        "<!-- GENERATED by scripts/status/render_status.py from status/status.toml. Do not edit. -->",
        f"# Project Status — {project['name']}",
        "",
        f"**Current phase:** {project['current_phase']} · **Updated:** {project['updated']} · "
        f"**Target:** {project['target_hardware']}",
        "",
        f"**Tasks:** {_bar(*_progress(all_tasks), width=20)} · "
        f"**Definition of Done (spec §83):** {_bar(sum(d['done'] for d in dod), len(dod), width=20)}",
        "",
        "## Phases",
        "",
        "| Phase | Name | Status | Modules | Tasks |",
        "|---|---|---|---|---|",
    ]
    for p in data["phases"]:
        in_phase = [m for m in modules if p["id"] in m.get("phases", [])]
        tasks = [t for m in in_phase for t in m.get("tasks", [])]
        marker = " ◀" if p["id"] == project["current_phase"] else ""
        out.append(
            f"| **{p['id']}**{marker} | {p['name']} | {ICONS[p['status']]} {p['status']} | "
            f"{', '.join(m['id'] for m in in_phase)} | {_bar(*_progress(tasks))} |"
        )

    out += [
        "",
        "## Modules",
        "",
        "| ID | Module | Phases | Status | Owner | Progress | Blocked by |",
        "|---|---|---|---|---|---|---|",
    ]
    for m in modules:
        out.append(
            f"| {m['id']} | {m['name']} | {', '.join(m.get('phases', []))} | "
            f"{ICONS[m['status']]} {m['status']} | {m.get('owner') or '—'} | "
            f"{_bar(*_progress(m.get('tasks', [])))} | {m.get('blocked_by') or ''} |"
        )

    out += ["", "## Active & blocked tasks", ""]
    active = [
        (m["id"], t)
        for m in modules
        for t in m.get("tasks", [])
        if t["status"] in {"DOING", "BLOCKED"} or (m["status"] == "IN_PROGRESS" and t["status"] == "TODO")
    ]
    if active:
        out += [f"- [ ] **{mid}** {t['title']} — {t['status']}" for mid, t in active]
    else:
        out.append("_None._")

    out += ["", "## Definition of Done (spec §83)", ""]
    out += [f"- [{'x' if d['done'] else ' '}] {d['item']} ({d['module']})" for d in dod]
    out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="exit 1 if STATUS.md is out of date")
    args = parser.parse_args()

    with SOURCE.open("rb") as fh:
        data = tomllib.load(fh)
    try:
        validate(data)
    except StatusError as exc:
        print(exc, file=sys.stderr)
        return 1

    rendered = render(data)
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != rendered:
            print("status/STATUS.md is stale; run: python scripts/status/render_status.py", file=sys.stderr)
            return 1
        print("status/STATUS.md is up to date.")
        return 0

    TARGET.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"Wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
